# Generated by Django 6.0.2 on 2026-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя в админке')),
                ('css_class', models.CharField(max_length=100, unique=True, verbose_name='CSS Класс')),
                ('target_area', models.CharField(choices=[('all', 'Общий (Для всех)'), ('portfolio', 'Только Портфолио'), ('experience', 'Только Опыт')], default='all', max_length=20)),
                ('attr_type', models.CharField(choices=[('layout', 'Размер / Сетка'), ('state', 'Состояние / Статус'), ('visual', 'Визуал / Тема'), ('typography', 'Текст')], default='visual', max_length=20)),
            ],
            options={
                'verbose_name': 'Атрибут стиля',
                'verbose_name_plural': 'Библиотека стилей',
            },
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Для URL и фильтров', unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('backend', 'Backend (Python/Core)'), ('database', 'Database / Cache'), ('frontend', 'Frontend / UI'), ('devops', 'DevOps / Infrastructure'), ('tools', 'Tools / Quality'), ('project_status', 'Статус Проекта (Dev, Prod, Support)'), ('project_type', 'Тип Проекта (Open Source, Startup)'), ('other', 'Other')], default='other', max_length=20, verbose_name='Категория')),
                ('icon_class', models.CharField(blank=True, help_text='Например: devicon-python-plain', max_length=50, verbose_name='CSS класс иконки')),
                ('color_hex', models.CharField(blank=True, help_text='#FFFFFF', max_length=7, verbose_name='Цвет (HEX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Тег / Технология',
                'verbose_name_plural': 'Справочник тегов',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
