# Generated by Django 6.0.2 on 2026-02-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tab_filename', models.CharField(help_text='Например: clients.py', max_length=50, verbose_name='Имя файла (Tab)')),
                ('tab_icon_text', models.CharField(default='PY', max_length=10, verbose_name='Иконка (Текст)')),
                ('tab_icon_class', models.CharField(help_text='gold, blue, green...', max_length=50, verbose_name='CSS класс иконки')),
                ('section_number', models.CharField(default='01', max_length=5, verbose_name='Номер секции')),
                ('section_title', models.CharField(help_text='CLIENT SOLUTIONS', max_length=100, verbose_name='Заголовок секции')),
                ('section_title_en', models.CharField(help_text='CLIENT SOLUTIONS', max_length=100, null=True, verbose_name='Заголовок секции')),
                ('section_title_ru', models.CharField(help_text='CLIENT SOLUTIONS', max_length=100, null=True, verbose_name='Заголовок секции')),
                ('theme_class', models.CharField(help_text='theme-gold, theme-blue...', max_length=50, verbose_name='CSS класс темы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, help_text='Markdown или HTML для страницы проекта', verbose_name='Полное описание')),
                ('content_en', models.TextField(blank=True, help_text='Markdown или HTML для страницы проекта', null=True, verbose_name='Полное описание')),
                ('content_ru', models.TextField(blank=True, help_text='Markdown или HTML для страницы проекта', null=True, verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('dev', 'В разработке'), ('prod', 'В продакшене'), ('support', 'В поддержке'), ('archived', 'Архив'), ('concept', 'Концепт / MVP')], default='dev', max_length=20, verbose_name='Статус')),
                ('project_type', models.CharField(choices=[('commercial', 'Коммерческий'), ('startup', 'Стартап'), ('opensource', 'Open Source'), ('pet', 'Pet Project'), ('enterprise', 'Enterprise')], default='pet', max_length=20, verbose_name='Тип проекта')),
                ('link_demo', models.URLField(blank=True, verbose_name='Demo URL')),
                ('link_github', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('is_featured', models.BooleanField(default=False, help_text='Поднимает вес проекта', verbose_name='Избранное')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portfolio.category', verbose_name='Категория')),
                ('style_visual', models.ForeignKey(blank=True, limit_choices_to={'attr_type': 'visual'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_visual', to='system.styleattribute', verbose_name='Стиль (Визуал)')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='system.techtag', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
